export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Hi, I\'m Camille',
    headline: 'Web designer based in Los Angeles, CA.',
    description: 'I develop websites with passion, creativity, and user experience in mind. With eye-catching pages that draw in your end users, you\'ll truly see your vision come to life!',
    buttonLabel: 'Learn More About Me',
    imgStart: false,
    img: "https://i.ibb.co/3CNLs7P/svg-2.png",
    alt: 'Girl Illustration',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'work',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Check out my work',
    headline: 'Projects made with passion',
    buttonLabel: 'Check out my work',
    description: 'Officia do officia ea do ullamco quis nisi deserunt adipisicing officia aute qui eiusmod in. Do veniam est mollit laborum duis anim laboris pariatur proident non do occaecat culpa tempor.',
    imgStart: true,
    img: "https://i.ibb.co/CmdWVMz/undraw-Portfolio-re-qwm5.png",
    alt: 'Portfolio Illustration',
    primary: false,
    dark: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'contact',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Project in mind?',
    headline: 'Let\'s work together!',
    buttonLabel: 'Contact Me',
    description: 'I love working with new people and bringing ideas to life. Let\'s turn your dream into reality with a responsive and beautiful website. ',
    imgStart: false,
    img: "https://i.ibb.co/gMFyrXc/undraw-contact-us-15o2.png",
    alt: 'Contact Illustration',
    dark: true,
    primary: true,
    darkText: false,
}