import {
  burger,
  cooking,
  draw,
  fitness,
  game,
  login,
  mint,
  responsive,
} from '../../../../assets/images';

export const projects = [
  {
    id: 'better',
    title: 'Better.',
    languages: ['javascript', 'python', 'css'],
    img: fitness,
    alt: 'Better. Project',
    git: '//www.github.com/camillebrown/Better-frontend',
    url: '//better-you-app.herokuapp.com/',
    classname: '',
  },
  {
    id: 'cookbook',
    title: 'Cookbook Curator',
    languages: ['nodejs', 'postgresql', 'css'],
    img: cooking,
    alt: 'Cookbook Curator Project',
    git: '//www.github.com/camillebrown/CookbookCurator',
    url: '//cookbook-curator.herokuapp.com/',
    classname: 'cook',
  },
  {
    id: 'game',
    title: 'Got The Beat!',
    languages: ['javascript', 'express', 'css'],
    img: game,
    alt: 'Got the Beat Project',
    git: '//www.github.com/camillebrown/GOT-THE-BEAT-GAME',
    url: '//camillebrown.github.io/GOT-THE-BEAT-GAME/',
    classname: '',
  },
  {
    id: 'ck-login',
    title: 'Credit Key Login',
    languages: ['ruby', 'sass', 'rails'],
    img: login,
    alt: 'Better. Project',
    git: '//www.github.com/camillebrown/ck-login',
    url: null,
    classname: 'login',
  },
  {
    id: 'mint',
    title: 'Mint & Honey',
    languages: ['react', 'css', 'javascript'],
    img: mint,
    alt: 'Mint & Honey Landing Page',
    git: '//www.github.com/camillebrown/mint-and-honey',
    url: '//mintandhoney.netlify.app',
    classname: 'mint',
  },
  {
    id: 'gpt3',
    title: 'GPT-3 Responsive',
    languages: ['javascript', 'css'],
    img: responsive,
    alt: 'GPT3 Responsive Design',
    git: '//www.github.com/camillebrown/gpt3-responsive',
    url: '//gpt-template-redesign.netlify.app/',
    classname: 'responsive',
  },
  {
    id: 'burger',
    title: 'Burger Stack',
    languages: ['react', 'javascript'],
    img: burger,
    alt: 'React Burger Stack Project',
    git: '//www.github.com/camillebrown/react-burger-stacker',
    url: null,
    classname: 'burger',
  },
  {
    id: 'hangman',
    title: 'Python Hangman',
    languages: ['python'],
    img: draw,
    alt: 'Hangman Python Practice',
    git: '//www.github.com/camillebrown/hangman-python',
    url: null,
    classname: 'hangman',
  },
];
